---
- name: Template the roadrunner config
  notify: Restart roadrunner
  ansible.builtin.template:
    src: roadrunner/rr.yaml
    dest: "{{ roadrunner.prefix.config }}/rr.yaml"
    owner: root
    mode: "0644"

- name: Start and enable the roadrunner service
  ansible.builtin.service:
    name: roadrunner
    state: started
    enabled: yes
