---
- name: Template the roadrunner config
  notify: Restart roadrunner
  ansible.builtin.template:
    src: roadrunner/rr.yaml
    dest: "{{ roadrunner.prefix.config }}/rr.yaml"
    owner: root
    mode: "0644"

- name: Start and enable the roadrunner service
  ansible.builtin.service:
    name: roadrunner
    state: started
    enabled: yes

- name: Handle RR restart (debug)
  block:
  - name: Reload changes in configuration and restart docker service
    register: roadrunner_restart_result
    ansible.builtin.service:
      name: roadrunner
      state: restarted

  - name: Print to console
    ansible.builtin.debug:
      msg: "{{ roadrunner_restart_result.stdout }}"
  rescue:
    - name: Get errors
      changed_when: no
      ansible.builtin.command: 
        cmd: journalctl -xeu roadrunner.service
      register: err_msg

    - name: Print error message to console
      ansible.builtin.debug:
        msg: "{{ err_msg.stdout }}"
