---
- name: Make sure that the roadrunner config folder exists
  file:
    dest: "{{ roadrunner.prefix.config }}"
    state: directory

- name: Template the roadrunner config
  notify: Restart roadrunner
  template:
    src: roadrunner/rr.yaml
    dest: "{{ roadrunner.prefix.config }}/rr.yaml"
    owner: proserver

- name: Start and enable the roadrunner service
  service:
    name: roadrunner
    state: started
    enabled: yes
