---
- name: Configure the system for Roadrunner
  ansible.builtin.include_tasks: setup.yml

- name: Configure Debian/Ubuntu for Roadrunner
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: setup-Debian.yml

- name: Configure FreeBSD for Roadrunner
  when: ansible_system == 'FreeBSD'
  ansible.builtin.include_tasks: setup-FreeBSD.yml

- name: Configure Roadrunner
  ansible.builtin.include_tasks: config.yml
