---
- name: Create the /var/opt folder (FreeBSD)
  when: ansible_system == "FreeBSD"
  ansible.builtin.file:
    state: directory
    name: "/var/opt"
    owner: root
    mode: "0755"

- name: Make sure that the roadrunner folders are created
  when: ansible_system == "FreeBSD"
  ansible.builtin.file:
    state: directory
    name: "{{ item }}"
  loop:
    - "{{ roadrunner.prefix.bin }}"
    - "{{ roadrunner.prefix.config }}"

- name: Create the roadrunner config folders
  ansible.builtin.file:
    state: directory
    name: "{{ roadrunner.prefix.config }}/{{ item.key }}"
    owner: "proserver"
    group: "proserver"
    mode: "0755"
  loop: "{{ roadrunner.config | dict2items }}"
