---
- name: Download and install the roadrunner v{{ roadrunner.version }} FreeBSD package
  ansible.builtin.unarchive:
    remote_src: yes
    src: https://github.com/roadrunner-server/roadrunner/releases/download/v{{ roadrunner.version }}/roadrunner-{{ roadrunner.version }}-freebsd-amd64.tar.gz
    dest: "{{ roadrunner.prefix.bin }}"

- name: Template supervisord configuration for Roadrunner
  ansible.builtin.template:
    src: supervisord.d/roadrunner.conf
    dest: "{{ supervisord.prefix.config }}/roadrunner.conf"
    owner: root
    mode: "0644"
  notify: Restart Supervisord

- name: Allow the user proserver to control the roadrunner service (FreeBSD)
  ansible.builtin.copy:
    owner: root
    mode: "0644"
    content: |
        proserver ALL = NOPASSWD: /usr/local/bin/supervisorctl restart roadrunner
        proserver ALL = NOPASSWD: /usr/local/bin/supervisorctl stop roadrunner
        proserver ALL = NOPASSWD: /usr/local/bin/supervisorctl start roadrunner
    dest: /usr/local/etc/sudoers.d/proserver-restart-roadrunner
