---
- name: Download and install the roadrunner v{{ roadrunner.version }} freebsd package
  ansible.builtin.unarchive:
    remote_src: yes
    src: https://github.com/roadrunner-server/roadrunner/releases/download/v{{ roadrunner.version }}/roadrunner-{{ roadrunner.version }}-freebsd-amd64.tar.gz
    dest: "{{ roadrunner.prefix.bin }}"

- name: Install the roadrunner systemd service
  notify: Restart roadrunner
  ansible.builtin.template:
    owner: root
    mode: "0644"
    src: systemd/roadrunner.service
    dest: /etc/systemd/system/roadrunner.service

- name: Allow the user proserver to control the roadrunner service (Linux)
  ansible.builtin.copy:
    owner: root
    mode: "0644"
    content: |
        proserver ALL = NOPASSWD: /bin/systemctl start roadrunner
        proserver ALL = NOPASSWD: /bin/systemctl status roadrunner
        proserver ALL = NOPASSWD: /bin/systemctl stop roadrunner
        proserver ALL = NOPASSWD: /bin/systemctl restart roadrunner
    dest: "{{ roadrunner.prefix.sudoers }}/proserver-restart-roadrunner"
    validate: 'bash -c "cat /etc/sudoers %s | visudo -cf-"'
