---
- name: Download and install the roadrunner v{{ roadrunner.version }} deb package
  register: roadrunner_install_binary_result
  ansible.builtin.apt:
    deb: https://github.com/roadrunner-server/roadrunner/releases/download/v{{ roadrunner.version }}/roadrunner-{{ roadrunner.version }}-linux-amd64.deb

- name: Allow the user proserver to control the roadrunner services (Linux)
  ansible.builtin.copy:
    owner: root
    mode: "0644"
    content: |
        proserver ALL = NOPASSWD: /bin/systemctl start roadrunner@*
        proserver ALL = NOPASSWD: /bin/systemctl status roadrunner@*
        proserver ALL = NOPASSWD: /bin/systemctl stop roadrunner@*
        proserver ALL = NOPASSWD: /bin/systemctl restart roadrunner@*
    dest: "{{ roadrunner.prefix.sudoers }}/proserver-restart-roadrunner"
    validate: 'bash -c "cat /etc/sudoers %s | visudo -cf-"'
