---
- name: Create the roadrunner folders
  ansible.builtin.file:
    state: directory
    name: "{{ item }}"
    owner: "{{ 'proserver' if 'www' in item else 'root' }}"
    mode: "0755"
  loop: "{{ roadrunner.prefix.values() }}"
