---
- name: Converge
  hosts: all
  vars:
    system:
      features:
        proserver_user: yes
  tasks:
    - name: "Include ansible-proserver-roadrunner"
      ansible.builtin.include_role:
        name: "ansible-proserver-roadrunner"
