---
- name: Converge
  hosts: all
  environment:
    GITHUB_ACTIONS: "maybe"
  vars:
    php:
      install_composer: yes
    roadrunner:
      config:
        main:
    system:
      features:
        proserver_user: yes
  tasks:
    - name: "Include ansible-proserver-roadrunner"
      ansible.builtin.include_role:
        name: "ansible-proserver-roadrunner"
