---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Create the current_release folder
      ansible.builtin.file:
        dest: "{{ item }}"
        state: "directory"
        owner: proserver
        mode: "0755"
      loop: 
        - "/var/www/current"
        - "/var/www/current/public"

    - name: Copy the example PHP script
      ansible.builtin.copy:
        owner: proserver
        mode: "0644"
        src: "app.php"
        dest: "/var/www/current/app.php"

    - name: Initialize the composer project
      community.general.composer:
        command: create-project
        arguments: "punktde/roadrunner-test /var/www/current ~1.0"
        working_dir: "/var/www/current"
        prefer_dist: true

    - name: Install PHP dependencies
      community.general.composer:
        command: require
        arguments: "{{ item }}"
        working_dir: "/var/www/current"
      loop:
        - "nyholm/psr7"
        - "spiral/roadrunner"
        - "spiral/roadrunner-http"

    - name: Enable and start the roadrunner-main service
      community.general.supervisorctl:
        name: "roadrunner-main"
        state: "present"
        stop_before_removing: yes

    - name: Check that a page returns successfully but fail if the word AWESOME is not in the page contents
      ansible.builtin.uri:
        url: http://localhost:8080
        return_content: true
      register: this
      failed_when: this is failed or "'Hello world' not in this.content"
