version: '2.7'

rpc:
  listen: tcp://127.0.0.1:{{ roadrunner.port.rpc }}

server:
  command: "php app.php"
  relay: pipes

http:
  address: 0.0.0.0:{{ roadrunner.port.http }}
  middleware: [ "gzip", "static" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  pool:
    num_workers: 4
    supervisor:
      max_worker_memory: 100

jobs:
  consume: [ ]
  pool:
    num_workers: 2
    supervisor:
      max_worker_memory: 100

kv:
  local:
    driver: memory
    config:
      interval: 60
  redis:
    driver: redis
    config:
      addrs:
        - localhost:6379

metrics:
  address: localhost:{{ roadrunner.port.metrics }}
